// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnpxxxoffgqznwzihnwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ucHh4eG9mZmdxem53emlobnd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTQ5MTIsImV4cCI6MjA2Mzc3MDkxMn0.GVEsjWXA2NQ6_P31H8OOuTkf9qCuY7IYJwlDQvVDblc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);